# Generated by Django 3.2.12 on 2022-09-15 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
