# Generated by Django 3.2.12 on 2022-10-17 15:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221017_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile/photos/', verbose_name='Photo'),
        ),
    ]
