# Generated by Django 3.2.12 on 2022-10-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2022-01-01', verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='11:11', verbose_name='Time'),
            preserve_default=False,
        ),
    ]
